#!/bin/bash 

PWD="$(pwd)"
OMNETPPINI=$PWD/$1
CONFIG=$2
SIMULATIONTIME=$3

echo "$PWD/sim.out"


cd ~/omnet-workspace/protocol
make MODE=release 
cd simulations/
pwd
../src/protocol -u Cmdenv -c $CONFIG --sim-time-limit "$SIMULATIONTIME" $OMNETPPINI 

cd $PWD







